### ISSUE TITLE
More info on why login failed

### ISSUE THREAD

**Issue by garethcmurphy** [SciCatProject/catanie#470]
## Issue Name
More info on why login failed
### Current Behaviour
User sees authenticaiton failed

### Expected Behaviour
User gets specific information such as incorrect password

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by lukegorman** [comment]
needs backend changes/ loopback changes

**Comment by nguyenlinhlinh** [comment]
Hi @stephan271  and @henrikjohansson712, I took a look at the current library we are using for ldap authentication. I can see that it will always return Invalid username/password if it it fails to find username and/or the password is wrong. For connection error it throws an exception which result HTTP code 500. If we want to have more specific messages rather than these two we might need to implement our own function and provided it to loopback library through providers.json. However before trying this I want to know if you think we should showing more specific messages rather than the two mentioned above because too specific messages will also expose the site for security issues.

**Comment by henrikjohansson712** [comment]
@nguyenlinhlinh As you say, I don't think we want messages that are more specific than that. It should be enough to know that the login failed either due to problems with the connection or due to entering the wrong credentials.

**Comment by nguyenlinhlinh** [comment]
@henrikjohansson712 Ok thank. Then I will only add an extra message for connection error and will not try to modify that in the backend.
