### ISSUE TITLE
Input on alternative view for scientific metadata

### ISSUE THREAD

**Issue by nguyenlinhlinh** [SciCatProject/catanie#727]
## Issue Name
I have added some styling to the tree view but I think it doesn't look good. Therefore I need some input from you. Please feel free to give comment on how you think the view should look like or if there are some features you want to have. I just tagged @henrikjohansson712  & @stephan271  but everyone's comment are welcomed.
### Summary
The view looks like in the picture. The user can search for properties that have for example the word "code" in it. The result shows up these properties and if it is a sub field of another property it's parent property will be expanded. 

![Screenshot 2021-02-26 at 09 53 20](https://user-images.githubusercontent.com/17545757/109279138-aef8f980-7819-11eb-9375-24f0d021cce3.png)

**Comment by stephan271** [comment]
Thanks for the work ! For me the view looks good enough to let us make further tests with the actual editing.
How do you plan to display physical quantities with units ? Would the value and unit appear on the same line (I would prefer this). I also noticed that there keys shown, which do not have "code" in them. Can you explain why ?

**Comment by nguyenlinhlinh** [comment]
Hi @stephan271 , I am thinking of displaying the unit next to value if that is ok or do you mean in the same line but in another column? about the keys that don't have "code" in them, I was unsure if they should show up or not because they are siblings to keys with code in it. Maybe showing them will only cause confusion so I have removed them and now it looks like this. 
![Screenshot 2021-03-01 at 08 21 15](https://user-images.githubusercontent.com/17545757/109465296-3f2c7e00-7a68-11eb-93bd-53ee842fe123.png)

**Comment by stephan271** [comment]
Displaying the unit next to the value without an extra column is fine in view mode

**Comment by nguyenlinhlinh** [comment]
@stephan271 If I remember correctly at PSI the data structure is different from ESS. How different is it? Could you give me an example of the structure?

**Comment by nguyenlinhlinh** [comment]
Thank, In the examples from PSI I see some quantities just have "v" & "u" fields while the other "value" & "unit". The code I wrote expects field "value" "unit" so it  won't work on "v" and "u". with "v" and "u" the tree might looks like this.
```
Ring current
  v: 0.4
  u: A
```
instead of 
```
Ring current        0.4 [A]
```
I also see that some field are in camelCase while other are words. Are there any reason while? My plan is to convert what user type in to camelCase automatically which means "Ring curent" becomes "ringCurrent" in database and showing "Ring Current" to user. 
```
"scientificMetadata": {
  "beamlineParameters": {
      "Monostripe": "Ru/C",
      "Ring current": {
          "v": 0.402246,
          "u": "A"
      },
      "Beam energy": {
          "v": 22595,
          "u": "eV"
      }
  },
```

**Comment by stephan271** [comment]
The v/u syntax above is from the time before we agreed on value/unit, so we will need to modify our data to make it consistent. Therefore you do not need to take this into account in software.
Concerning the auto-camelcase: I think any automatic transformation, especially when it is hidden from the user , is too dangerous. I expect that will cause confusion and some unwanted sideeffects in the long wrong. Currently we have no rules for the names of the keys. Enforcing naming convention could however be part of the ingest logic (either in the ingest command line tools or may be even inside the core API logic). If any of the applied rules are violated the data should be rejected rather than automatically transformed, IMHO.
May be we need a more extended discussion where any such validation/schema verification logic should be implemented in future ...

**Comment by stephan271** [comment]
Not sure if this answers all questions, close the issue for now, can be reopened if required
